#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : casync
Version  : v2.219.8f6c84
Release  : 4
URL      : https://github.com/systemd/casync/archive/a8f6c841ccfe59ca8c68aad64df170b64042dce8/v2-219-ga8f6c84.tar.gz
Source0  : https://github.com/systemd/casync/archive/a8f6c841ccfe59ca8c68aad64df170b64042dce8/v2-219-ga8f6c84.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: casync-bin = %{version}-%{release}
Requires: casync-config = %{version}-%{release}
Requires: casync-data = %{version}-%{release}
Requires: casync-license = %{version}-%{release}
Requires: casync-man = %{version}-%{release}
Requires: acl-lib
BuildRequires : Sphinx
BuildRequires : acl-dev
BuildRequires : bash-completion-dev
BuildRequires : buildreq-meson
BuildRequires : pkgconfig(bash-completion)
BuildRequires : pkgconfig(fuse)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(liblzma)
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(libzstd)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(zlib)
BuildRequires : rsync

%description
# casync — Content Addressable Data Synchronizer
What is this?
1. A combination of the rsync algorithm and content-addressable storage

%package bin
Summary: bin components for the casync package.
Group: Binaries
Requires: casync-data = %{version}-%{release}
Requires: casync-config = %{version}-%{release}
Requires: casync-license = %{version}-%{release}

%description bin
bin components for the casync package.


%package config
Summary: config components for the casync package.
Group: Default

%description config
config components for the casync package.


%package data
Summary: data components for the casync package.
Group: Data

%description data
data components for the casync package.


%package license
Summary: license components for the casync package.
Group: Default

%description license
license components for the casync package.


%package man
Summary: man components for the casync package.
Group: Default

%description man
man components for the casync package.


%prep
%setup -q -n casync-a8f6c841ccfe59ca8c68aad64df170b64042dce8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568688935
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dselinux=false  builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
ninja -v -C builddir test

%install
mkdir -p %{buildroot}/usr/share/package-licenses/casync
cp LICENSE.LGPL2.1 %{buildroot}/usr/share/package-licenses/casync/LICENSE.LGPL2.1
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)
/usr/lib/casync/protocols/casync-ftp
/usr/lib/casync/protocols/casync-http
/usr/lib/casync/protocols/casync-https
/usr/lib/casync/protocols/casync-sftp

%files bin
%defattr(-,root,root,-)
/usr/bin/casync

%files config
%defattr(-,root,root,-)
/usr/lib/udev/rules.d/75-casync.rules

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/casync

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/casync/LICENSE.LGPL2.1

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/casync.1
