#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : casync
Version  : 2
Release  : 1
URL      : https://github.com/systemd/casync/archive/v2.tar.gz
Source0  : https://github.com/systemd/casync/archive/v2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: casync-bin
Requires: casync-config
Requires: casync-license
Requires: casync-man
Requires: acl-lib
BuildRequires : Sphinx
BuildRequires : acl-dev
BuildRequires : buildreq-meson
BuildRequires : pkgconfig(fuse)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(liblzma)
BuildRequires : pkgconfig(libzstd)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(zlib)
BuildRequires : rsync
Patch1: 0001-Fix-segv-in-ca_remote_forget_chunk.patch
Patch2: 0002-Fix-build-without-selinux-and-refuse-with-selinux-wh.patch
Patch3: 0003-src-caformat.h-do-not-set-selinux-flags-by-default-w.patch
Patch4: 0004-cachunker-round-the-expected-average-chunk-size-135.patch
Patch5: 0005-meson-drop-ffast-math-from-gcc-options-136.patch

%description
# casync â Content Addressable Data Synchronizer
What is this?
1. A combination of the rsync algorithm and content-addressable storage

%package bin
Summary: bin components for the casync package.
Group: Binaries
Requires: casync-config
Requires: casync-license
Requires: casync-man

%description bin
bin components for the casync package.


%package config
Summary: config components for the casync package.
Group: Default

%description config
config components for the casync package.


%package license
Summary: license components for the casync package.
Group: Default

%description license
license components for the casync package.


%package man
Summary: man components for the casync package.
Group: Default

%description man
man components for the casync package.


%prep
%setup -q -n casync-2
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532483165
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --prefix /usr --buildtype=plain -Dselinux=false  builddir
ninja -v -C builddir

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
ninja -v -C builddir test

%install
mkdir -p %{buildroot}/usr/share/doc/casync
cp LICENSE.LGPL2.1 %{buildroot}/usr/share/doc/casync/LICENSE.LGPL2.1
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)
/usr/lib/casync/protocols/casync-ftp
/usr/lib/casync/protocols/casync-http
/usr/lib/casync/protocols/casync-https
/usr/lib/casync/protocols/casync-sftp

%files bin
%defattr(-,root,root,-)
/usr/bin/casync

%files config
%defattr(-,root,root,-)
/usr/lib/udev/rules.d/75-casync.rules

%files license
%defattr(-,root,root,-)
/usr/share/doc/casync/LICENSE.LGPL2.1

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/casync.1
